//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Швейная_фабрика
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FactoryEntities1 : DbContext
    {
        public FactoryEntities1()
            : base("name=FactoryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cloth> Cloth { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Furniture> Furniture { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductsInOrder> ProductsInOrder { get; set; }
        public virtual DbSet<Structure> Structure { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Write_downs> Write_downs { get; set; }
    }
}
