//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Швейная_фабрика
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsInOrder
    {
        public int IDProd { get; set; }
        public string ArticleID { get; set; }
        public string ClothID { get; set; }
        public string FurnitureID { get; set; }
        public double Quantity { get; set; }
        public Nullable<int> NumOrder { get; set; }
        public Nullable<int> Turn { get; set; }
        public string Place { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual Furniture Furniture { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Products Products { get; set; }
    }
}
