//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Швейная_фабрика
{
    using System;
    using System.Collections.Generic;
    
    public partial class Write_downs
    {
        public int IdWrite { get; set; }
        public string ArticleID { get; set; }
        public string ClothID { get; set; }
        public Nullable<int> Cost { get; set; }
        public double Quantity { get; set; }
        public string Reason { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual Products Products { get; set; }
    }
}
